name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: SetapiKey
      run: nuget setapikey ${{secrets.NUGET_SECRET}} -Source https://api.nuget.org/v3/index.json
    - name: Install dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build --configuration Release --no-restore src
    - name: Setup .NET @ Latest
      uses: actions/setup-dotnet@v2
      with:
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_SECRET}}  
    - name: Build solution and generate NuGet package
      run: |  
        cd src
        dotnet pack -c Release -o out  
    - name: Push Nuget
      run: dotnet nuget push ./src/out/*.nupkg --skip-duplicate --no-symbols true
